- hosts: master
  become: yes
  tasks:
    - name: Create Staging Namespace
      become: yes
      become_user: marco
      shell: kubectl get ns stagging  -ojsonpath='{.status.phase}' | grep Active ||  kubectl create ns stagging
      args:
        chdir: $HOME
        creates: ns_creation.txt
    - name: Create Production Namespace
      become: yes
      become_user: marco
      shell:  kubectl get ns stagging -ojsonpath='{.status.phase}' | grep Active ||  kubectl create ns production
    - name: Create Guestbook in Staging Namespace
      become: yes
      become_user: marco
      shell: kubectl -n stagging apply -f https://raw.githubusercontent.com/kubernetes/examples/master/guestbook/all-in-one/guestbook-all-in-one.yaml
      args:
        chdir: $HOME
        creates: guestbook_staging.txt
    - name: Create Guestbook in production Namespace
      become: yes
      become_user: marco
      shell: kubectl -n production apply -f https://raw.githubusercontent.com/kubernetes/examples/master/guestbook/all-in-one/guestbook-all-in-one.yaml
      args:
        chdir: $HOME
        creates: guestbook_staging.txt
      
      
