- hosts: all
  become: yes
  tasks:

   - name: disable SELinux
     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

       
   - name: stop firewalld
     service:
       name: firewalld
       enabled: no
       state: stopped

   - name: unmount any swap 
     mount:
       path: swap
       fstype: swap
       state: absent

       
       
