- hosts: all
  become: yes
  tasks:

   - name: disable SELinux
     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
       
   - name: stop firewalld
     service:
       name: firewalld
       enabled: no
       state: stopped

   - name: unmount any swap 
     mount:
       path: swap
       fstype: swap
       state: absent

       
       
