- hosts: master
  become: yes
  tasks:
    - name: Create metric 1
      become: yes
      become_user: marco
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/aggregated-metrics-reader.yaml
      args:
        chdir: $HOME
        creates: metric.txt
    - name: Create metric 2
      become: yes
      become_user: marco
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/auth-delegator.yaml
      args:
        chdir: $HOME
        creates: metric.txt
    - name: Create metric 3
      become: yes
      become_user: marco
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/auth-reader.yaml
      args:
        chdir: $HOME
        creates: metric.txt
    - name: Create metric 4
      become: yes
      become_user: marco
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-apiservice.yaml
      args:
        chdir: $HOME
        creates: metric.txt
    - name: Copy patched version of metris deploy onto cluster
      become: yes
      become_user: marco
      template:
        src: metrics-server-deployment.yaml
        dest: metrics-server-deployment.yaml
    - name: Create metric 5
      become: yes
      become_user: marco
      shell: kubectl apply -f metrics-server-deployment.yaml
      args:
        chdir: $HOME
        creates: metric.txt
    - name: Create metric 6
      become: yes
      become_user: marco
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/metrics-server-service.yaml
      args:
        chdir: $HOME
        creates: metric.txt
    - name: Create metric 7
      become: yes
      become_user: marco
      shell: kubectl apply -f  https://raw.githubusercontent.com/kubernetes-incubator/metrics-server/master/deploy/1.8%2B/resource-reader.yaml
      args:
        chdir: $HOME
        creates: metric.txt
