#!/usr/bin/env python3

import subprocess 
import sys
import os
import re
import json
import argparse

k8_user = "marco"
parser = argparse.ArgumentParser(description='Setup K8s environment and run some tests')

def ansibleSetup():

    try:
        print("#### Setting up the K8s cluster")
        subprocess.Popen(["ansible-playbook", "k8s_install_playbook.yaml", "-i", ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory", "--private-key=~/.ssh/google_compute_engine", "-u" ,k8_user,"--extra-vars","k8_user={}".format(k8_user)], env={"ANSIBLE_HOST_KEY_CHECKING": "False"}).wait()

        subprocess.Popen(["ansible-playbook", "cluster_playbook.yaml", "-i", ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory", "--private-key=~/.ssh/google_compute_engine", "-u" ,k8_user,"--extra-vars","k8_user={}".format(k8_user)], env={"ANSIBLE_HOST_KEY_CHECKING": "False"}).wait()
    except subprocess.CalledProcessError:
        sys.exit(-2)
    try:
        print("### Setting up the Ingress controller")
        subprocess.Popen(["ansible-playbook", "ingress_playbook.yaml", "-i", ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory", "--private-key=~/.ssh/google_compute_engine", "-u" ,k8_user,"--extra-vars","k8_user={}".format(k8_user)], env={"ANSIBLE_HOST_KEY_CHECKING": "False"}).wait()
    except subprocess.CalledProcessError:
        sys.exit(-2)
    try:
        print("### Setting up the metric controller")
        subprocess.Popen(["ansible-playbook", "metric_playbook.yaml", "-i", ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory", "--private-key=~/.ssh/google_compute_engine", "-u" ,k8_user,"--extra-vars","k8_user={}".format(k8_user)], env={"ANSIBLE_HOST_KEY_CHECKING": "False"}).wait()
    except subprocess.CalledProcessError:
        sys.exit(-2)
    try:
        print("### Setting up the guestbook")
        subprocess.Popen(["ansible-playbook", "guestbook_playbook.yaml", "-i", ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory", "--private-key=~/.ssh/google_compute_engine", "-u" ,k8_user,"--extra-vars","k8_user={}".format(k8_user)], env={"ANSIBLE_HOST_KEY_CHECKING": "False"}).wait()
    except subprocess.CalledProcessError:
        sys.exit(-2)

### setup the network

def networkSetup():

    try:
        subprocess.check_call(["gcloud", "compute", "target-pools", "create", "guest-pool"])
    except subprocess.CalledProcessError:
        print("target-pool already created")

    try:
        print("start")
        subprocess.Popen("gcloud compute target-pools add-instances guest-pool --instances master,worker1,worker2 --instances-zone us-central1-f",shell=True).wait()
        print("end")
    except subprocess.CalledProcessError:
        print("added instances to pool already")
        
    try:
        subprocess.check_call(["gcloud", "compute", "addresses", "create", "lb-ip", "--region", "us-central1"])
    except subprocess.CalledProcessError:
        print("static IP created already")
                           
    try:
        subprocess.Popen("gcloud compute forwarding-rules create www-rule --region us-central1 --ports 80 --address lb-ip --target-pool guest-pool",shell=True).wait()
    except subprocess.CalledProcessError:
        print("forwarding rule created already")

    try:
        subprocess.check_call(["gcloud", "compute", "firewall-rules", "create", "open", "--allow", "tcp:80"])
    except subprocess.CalledProcessError:
        print("firewall rule created already")

    lb_output = subprocess.getoutput('gcloud compute addresses list')

    for line in lb_output.splitlines():
        print("line: " + line)
        if re.match('^lb-ip',line):
            obj = re.search('(\d+\.\d+\.\d+\.\d+)',line)
            ip = obj.group()
            print("ip :" + ip )

    return ip




listing = subprocess.getoutput('ls -rt')

for file in listing.splitlines():
    if re.match('.*\.json$',file):
        theFile = file

with  open(theFile) as json_file:
    data = json.load(json_file)
print(data['project_id'])


os.environ.update({"PROJECT_ID": data['project_id'], "CREDENTIALS": theFile})


if len(sys.argv) > 1:

    vagrantCommand = sys.argv[1]

    if vagrantCommand == "ssh":
        if len(sys.argv) > 2:
            machine = sys.argv[2]
        else:
            machine = ""
        try:
            subprocess.Popen(['vagrant','ssh', machine], env=dict(os.environ) ).wait()
        except subprocess.CalledProcessError:
            sys.exit(-2)

    elif vagrantCommand == "provision":            
            
        try:
            subprocess.Popen(['vagrant','provision'], env=dict(os.environ) ).wait()

        except subprocess.CalledProcessError:
            sys.exit(-2)



    elif vagrantCommand == "up":

        try:
            subprocess.check_call(['gcloud',"auth","activate-service-account","--key-file={}".format(theFile)] )
            subprocess.check_call(['gcloud',"config","set","project",data['project_id'] ])
        except subprocess.CalledProcessError:
            sys.exit(-2)

        try:
            subprocess.check_call(['gcloud',"compute","config-ssh"] )
        except subprocess.CalledProcessError:
            sys.exit(-2)
                          
                
        print("starting vargrant")
        return_code = subprocess.call(['vagrant','up','--no-provision'], env=dict(os.environ) )
        print("finished vargrant")
        if return_code != 0 :
            print("Something went wrong in vagrant, exiting ...")
            sys.exit(2)

        try:
            subprocess.Popen(['vagrant','provision'], env=dict(os.environ) ).wait()

        except subprocess.CalledProcessError:
            sys.exit(-2)

            
            
#    Finally launch the ansible code:
        ansibleSetup()
#    And setup load balancer and firewall        
        ip_address = networkSetup()

        try:
            print("### Setting up static IP address")
            subprocess.Popen(["ansible-playbook", "patch_svc_playbook.yaml", "-i", ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory", "--private-key=~/.ssh/google_compute_engine", "-u" ,k8_user,"--extra-vars","k8_user={}".format(k8_user) ], env={"ANSIBLE_HOST_KEY_CHECKING": "False", "ip_address": ip_address }).wait()
        except subprocess.CalledProcessError:
            sys.exit(-2)


    elif vagrantCommand == "status":
        try:
            subprocess.Popen(['vagrant','status'], env=dict(os.environ) ).wait()
        except subprocess.CalledProcessError:
            sys.exit(-2)

    elif vagrantCommand == "halt":
        try:
            subprocess.Popen(['vagrant','halt'], env=dict(os.environ) ).wait()
        except subprocess.CalledProcessError:
            sys.exit(-2)

    elif vagrantCommand == "destroy":
        try:
            subprocess.Popen(['vagrant','destroy','-f'], env=dict(os.environ) ).wait()
        except subprocess.CalledProcessError:
            sys.exit(-2)

    elif vagrantCommand == "test":

        ip=''
        with open(".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory",mode='r') as fp:
            for line in fp:
                if re.match('^master',line):
                    obj = re.search('(\d+\.\d+\.\d+\.\d+)',line)
                    if obj:
                        ip = obj.group()

        try:
            print("ip: " + ip)


            lines = subprocess.Popen("ssh {} -i ~/.ssh/google_compute_engine kubectl get hpa -A --watch".format(ip),shell=True,stdout=subprocess.PIPE)
#            subprocess.Popen(["ab","-c","1000","-n","10000","http://stagging-guestbook.mstakx.io/"])
            while lines.poll() is None:
                line=lines.stdout.readline().strip().decode()
                print(line)
                
            
        except subprocess.CalledProcessError:
            sys.exit(-2)

            

        


    else:
        print(vagrantCommand + " is not a valid vagrant option or the key word \'test\' ")

else:
    print("I need an argument ...  ")
        

    
